Interpreter: interpreterP2.cpp S-exp.h Tokenizer.h IO.h Interpret.h S-exp.cpp Tokenizer.cpp IO.cpp Interpret.cpp
	g++ -o interpreterP2 interpreterP2.cpp Tokenizer.cpp IO.cpp S-exp.cpp Interpret.cpp


clean: 
	rm -rf interpreterP2