Interpreter: interpreter.cpp S-exp.h Tokenizer.h IO.h Interpret.h S-exp.cpp Tokenizer.cpp IO.cpp Interpret.cpp
	g++ -o interpreter interpreter.cpp Tokenizer.cpp IO.cpp S-exp.cpp Interpret.cpp


clean: 
	rm -rf interpreter